### ISSUE TITLE
Do we need the PID_integer class

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#1]
It inherits from ZRing<Integer> and adds a few features: mostly, gcd, lcm, rationalreconstruction, isDivisor, etc.

Shouldn't we move these functions to Givaro::ZRing<Integer> directly?

**Comment by Breush** [comment]
Things like RationalReconstruction are LinBox-dependent (have a look to ``algorithms/rational-solver.inl``). GCD does already exists inside Givaro.

**Comment by ClementPernet** [comment]
No, RationalReconstruction, is something one could expect from a ZRing, indepently from LinBox. The fact that currently, only LinBox rational solver uses it does not mean it should be offered in the Givaro ring.

Yes GCD exist in Givaro, but only as a function acting on integers. My question was about offering a gcd method in Givaro::ZRing, which makes sense.

My point is that there is no strong design reason for PID_integer to be defined in LinBox on top of Givaro's ZRing.

**Comment by Breush** [comment]
So, what do you propose:
- a specialization of ZRing<Integer> in Givaro with more abilities than other ZRing ;
- or a make all PID_integer functions available for all ZRing (generic)?

**Comment by ClementPernet** [comment]
I think we should move these features in Givaro in all cases, and more generally try to have as few field/rings as possible in LinBox and ideally remove the ring field directories to avoid user/developper confusion.

Then in Givaro, I would prefer the second option.
ZRing, means ring of integers. It is only generic wrt the type of representation for the underlying elements. As the ring of integers is a PID, I see no point in having a ZRing without these features.

**Comment by gmh33** [comment]
I agree with Clement, the PID integer functionality should be moved into givaro, and similar PID functionality should be implemented for givaro poly1.  Some linbox code (e.g. cra-early-multip) relies on PID_integer, but is used by some test code (I think test-det) that has been converted to use ZRing<Integer>, causing the test to fail to compile.

**Comment by ClementPernet** [comment]
I did the merge of PID-integer into Givaro::ZRing<Integer> in 4aa4c56.
The test suite, examples and benchmark should all work fine by now (except a bug in test-charpoly), which I'll now investigate.
