### ISSUE TITLE
test-qlup fails (sparse elimination)

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#10]
[pernet@nisqually] :~/Logiciels/linbox/tests > ./test-qlup -
Writing report data to cout (intermingled with brief report)

QLUP  test suite...
  Testing Sparse elimination qlup...
    Iteration 0...
      QLUPin Gaussian elimination with reordering...
            done (0.000980139 s)
        done (0.00141811 s)
    Iteration 1...
      QLUPin Gaussian elimination with reordering...
            done (0.000908852 s)
        done (0.00126195 s)
    FAILED (0.0028789 s)
  Testing Sparse elimination qlup solve...
    Iteration 0...
      QLUPin Gaussian elimination with reordering...
            done (0.000987053 s)
      Sparse Elimination Lower Triangular Unitary Solve...
            done (3.09944e-05 s)
      Sparse Elimination Upper Triangular Solve...
terminate called after throwing an instance of 'LinBox::LinboxError'
Aborted

**Comment by jgdumas** [comment]
Too large field by default.
Fixed with Modular<32_t,64_t>
