### ISSUE TITLE
segfault det sparse integer matrices

### ISSUE THREAD

**Issue by videlec** [linbox-team/linbox#104]
What I describe below concern the code that can be found at https://github.com/videlec/cylinbox that can be compiled against the last Sage version 8.2.beta2. It should be readable by people familiar with Cython.

The bug I want to report concerns the determinant of sparse integer matrices. More precisely, when the entries are big the function `det` segfaults. Here is such example with a 1x1 matrix with entry 2^26
```
sage: from linbox import linbox_integer_sparse_det
sage: m[0,0] = 2**26
sage: linbox_integer_sparse_det(m)
** BOOM **
```
The case of 2^25 is ok and the threshold 2^26 is quite mysterious to me (it is close to floating-point precision but not quite the same).

The matrix class I am using is `LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>>` (see [line 60 in linbox.pxd](https://github.com/videlec/cylinbox/blob/master/linbox.pxd#L60)) and the determinant function is the one from `linbox/solutions/det.h` (see [line 222 in linbox.pxd](https://github.com/videlec/cylinbox/blob/master/linbox.pxd#L222)).
  
Here is the traceback obtained from Cython 
[det_traceback.txt](https://github.com/linbox-team/linbox/files/1616670/det_traceback.txt)

**Comment by ClementPernet** [comment]
Hi Vincent. 2^26 seems indeed related to floating point precision (half the mantissa of double) which is used in many places in LinBox.
I can not reproduce the bug in pure LinBox C++ code for the moment (using v1.5.2). I'll give a try using cylinbox.

**Comment by videlec** [comment]
Better if it is on the cylinbox side :-) Could you please send me the pure LinBox code you wrote for this (with compilation instruction)? I can try to match what I have done in cylinbox.

**Comment by ClementPernet** [comment]
The following patch adds a regression test trying to replicate your bug.
```
diff --git a/tests/test-regression.C b/tests/test-regression.C
index 2703176..002078e 100644
--- a/tests/test-regression.C
+++ b/tests/test-regression.C
@@ -282,7 +282,14 @@ bool testBigScalarCharPoly(){
     ZZ.neg(Q[0],x);
     return PR.areEqual(P,Q);
 }
-
+bool testSparse1x1Det(){
+    Givaro::ZRing<Integer> ZZ;
+    SparseMatrix<Givaro::ZRing<Integer> > A(ZZ, 1, 1);
+    Integer x(1UL<<26);
+    A.setEntry(0,0,x);
+    Integer d;
+    return x == det(d,A);
+}
 int main (int argc, char **argv)
 {
     bool pass = true;
@@ -305,6 +312,6 @@ int main (int argc, char **argv)
     pass &= testZeroDimensionalCharPoly ();
     pass &= testZeroDimensionalMinPoly ();
     pass &= testBigScalarCharPoly ();
-
+    pass &= testSparse1x1Det ();
     return pass ? 0 : -1;
 }

```
Applied on v.1.5.2, it works fine on my side.

**Comment by videlec** [comment]
I added the Cython traceback to the description if it helps.

**Comment by videlec** [comment]
The test program hangs forever if you replace your function with
```
bool testSparse1x1Det(){
    bool pass = true;
    for (int i = 0; i < 1000; i++)
    {
        Givaro::ZRing<Integer> ZZ;
        SparseMatrix<Givaro::ZRing<Integer> > A(ZZ, 1, 1);
        Integer x(1UL<<26);
        A.setEntry(0,0,x);
        Integer d;
        pass &= (x == det(d,A));
    }
    return pass;
}
```

**Comment by videlec** [comment]
Il y a peut-être quelque chose de spécifique à la dimension 1. J'ai une erreur sur `test-det` avec dimension `n=1`.
```
$ ./test-det -n1
Erreur de segmentation (core dumped)
```
C'est possible de lancer gdb sur l'exécution du test? Quand on ouvre `test-det` on trouve un script pas clair et pas un exécutable binaire!

**Comment by vneiger** [comment]
Hello Vincent,
I don't know whether this is simply a typo in your message, so just in case: I think you will always have a segmentation fault if you do not use a space when you specify the dimension:
`./test-det -n 1`
(on my machine, -n2 or -n3 or -n4 etc. without a space all yield a segmentation fault).
That being said, on my machine I get the following error for n=1:
`Floating point exception (core dumped)`

**Comment by ClementPernet** [comment]
Hi,
test-det with -n 1 is indeed a bug but in the test-suite: line 187: 
`k =int( (size_t)rand () % (n / 2) );  ` results in a stupid large value for k, hence an access out of allocated memory in the following line.
To run gdb, you should indeed bypass the automatically generated test scripts by calling gdb on the ` .libs/test-det` binary.

**Comment by videlec** [comment]
Thanks to both of you! It seems that this `$ test-det -n 1` bug is unrelated to the segfault I see in cylinbox. I updated a more complete version of the Cython traceback [det_traceback.txt](https://github.com/linbox-team/linbox/files/1616670/det_traceback.txt) which traces the fault up to gmp.

**Comment by videlec** [comment]
It looks fine now, I propose to close the issue.
