### ISSUE TITLE
Sequential results for solveCRA and solve using BlasElimination are not consistent

### ISSUE THREAD

**Issue by ZHG2017** [linbox-team/linbox#107]
I used the attached scratched program to generate a matrix and a vector of random value then change one value with multiple precision integer value, the solve method and solveCRA method both using BlasElimination as method parameter do not give the same solution for the same linear system generated.

[test-seqCRA.txt](https://github.com/linbox-team/linbox/files/1614691/test-seqCRA.txt)

**Comment by jgdumas** [comment]
[intb.txt](https://github.com/linbox-team/linbox/files/1615790/intb.txt)

[intmat.txt](https://github.com/linbox-team/linbox/files/1615793/intmat.txt)

Probably a problem in Dixon lifting,

in the examples directory, 
> ./solve  intmat.txt intb.txt 
> ./solverat  intmat.txt intb.txt 
produce an erroneous result (this is not the case for with smaller numbers for this 1x1 matrix)
while
> ./sparsesolverat intmat.txt intb.txt 
>./solveCRA  intmat.txt intb.txt 
are correct.
