### ISSUE TITLE
1x1 integral determinant hangs forever

### ISSUE THREAD

**Issue by videlec** [linbox-team/linbox#109]
For the value `v = 1<<26` the following hangs forever
```
bool testSparse1x1Det(unsigned long v){
    bool pass = true;
    for (int iteration = 0; iteration < 1000; iteration++)
    {
        Givaro::ZRing<Integer> ZZ;
        SparseMatrix<Givaro::ZRing<Integer> > A(ZZ, 1, 1);
        Integer x(v);
        A.setEntry(0,0,x);
        Integer d; 
        pass &= (x == det(d,A));
    }
    return pass;
}
```
It looks fine for `v = 1<<25`.

This might involves randomness in the algorithm used for `det`. When printing the `iteration` variable one can see that it does not hang at the first step. And the step at which it hangs changes from time to time.

(found while digging for #104)
(possibly related to #118)

**Comment by jgdumas** [comment]
This one is now corrected (and present in test-regression)
