### ISSUE TITLE
determinant on diagonal sparse integer matrices hangs forever

### ISSUE THREAD

**Issue by videlec** [linbox-team/linbox#118]
(At least from the Sage interface) the determinant of the sparse 46 x 46 integer matrix (`LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>>` ) with only 2 on its diagonal hangs forever.

donwstream issue at [Sage trac ticket #23214, comment 11](https://trac.sagemath.org/ticket/23214#comment:11).
(possibly related to #109)

**Comment by jgdumas** [comment]
I have added the test in test-regression, commit 54d3ce4b7f2a772cee5dffca8c19d5773d7daa6d, 
but cannot reproduce the problem in LinBox.
