### ISSUE TITLE
Out of bounds vector accesses

### ISSUE THREAD

**Issue by jamesjer** [linbox-team/linbox#119]
Fedora recently added -D_GLIBCXX_ASSERTIONS to the compiler flags.  When linbox's test suite runs, several out of bounds vector accesses are caught by this.  In both linbox/matrix/densematrix/blas-matrix.inl and linbox/vector/blas-vector.h, there are many places where `_ptr` is set to `&_rep[0]`.  This is fine if `_rep` has size greater than 0, but it doesn't always; in the case where it is 0, reference to the zeroth element is not legal.  If C++11 or later can be assumed, then `_ptr` could be set to `_rep.data()` instead.

In addition, in linbox/matrix/sparsematrix/sparse-csr-matrix.h, line 1199 is a loop that looks like this:

`while(Ap_->_start[row_] == Ap_->_start[row_+1]) ++row_;`

Notice that the value of _row is not compared against any bounds.  This loop can fall off the end of the vector.  I suggest this replacement:

`while(row_+1 < Ap_->rowdim() && Ap_->_start[row_] == Ap_->_start[row_+1]) ++row_;`

**Comment by ClementPernet** [comment]
Thanks for your report. I've fixed these issues upstream.
