### ISSUE TITLE
FFT codes does not compile with AVX2

### ISSUE THREAD

**Issue by BastienVialla** [linbox-team/linbox#133]
On a fresh installation of LinBox, the file "examples/bench-new-fft.C" does not compile when linbox uses AVX2.

The file compiles when I replace 
`#if defined(__FFLASFFPACK_HAVE_AVX2_INSTRUCTIONS)`
by 
`#if 0`

Attached the compilation log.

[Log error.txt](https://github.com/linbox-team/linbox/files/2348997/Log.error.txt)

**Comment by pascalgiorgi** [comment]
this has been resolved in 2542a648358f54e5091a2925e5b4917a984bb447.

The FFT code is not yet handling modular<double,double>. This enhancement has to be done, I open a request.
