### ISSUE TITLE
Compilation error on OSX (new LinBox::DenseVector<Givaro::ZRing<Givaro::Integer>>)

### ISSUE THREAD

**Issue by vinklein** [linbox-team/linbox#138]
Compiling the code below works on linux but fails on OSX :
#main.cpp
```
#include <linbox/matrix/sparse-matrix.h>

int main() {

    LinBox::DenseVector<Givaro::ZRing<Givaro::Integer>> *res;
    Givaro::ZRing<Givaro::Integer> zz;
    long nbcols = 10;
    res = new LinBox::DenseVector<Givaro::ZRing<Givaro::Integer>>(zz, nbcols);
    return 0;
}
```

```
(sage-sh) admin@laptop:testlinboxBug$ gcc main.cpp -std=gnu++11 -I/usr/local/include -lstdc++ -lm -L /usr/local/lib -lgivaro -lgmp -lgmpxx -llinbox
In file included from main.cpp:1:
In file included from /Users/admin/sage/local/include/linbox/matrix/sparse-matrix.h:70:
In file included from /Users/admin/sage/local/include/linbox/matrix/sparsematrix/sparse-generic.h:80:
In file included from /Users/admin/sage/local/include/linbox/matrix/matrix-domain.h:68:
In file included from /Users/admin/sage/local/include/linbox/matrix/matrixdomain/blas-matrix-domain.h:51:
In file included from /Users/admin/sage/local/include/linbox/matrix/dense-matrix.h:79:
In file included from /Users/admin/sage/local/include/linbox/matrix/densematrix/blas-matrix.h:44:
/Users/admin/sage/local/include/linbox/vector/blas-vector.h:306:11: error: member reference base type 'const long'
      is not a structure or union
                        _size(V.size()),_1stride(1),_rep(V.size(), F.zero),_ptr(&_rep[0]),_field(&F)
                              ~^~~~~
main.cpp:8:15: note: in instantiation of function template specialization
      'LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::__1::vector<Givaro::Integer,
      std::__1::allocator<Givaro::Integer> > >::BlasVector<long>' requested here
    res = new LinBox::DenseVector<Givaro::ZRing<Givaro::Integer>>(zz, nbcols);
              ^
In file included from main.cpp:1:
In file included from /Users/admin/sage/local/include/linbox/matrix/sparse-matrix.h:70:
In file included from /Users/admin/sage/local/include/linbox/matrix/sparsematrix/sparse-generic.h:80:
In file included from /Users/admin/sage/local/include/linbox/matrix/matrix-domain.h:68:
In file included from /Users/admin/sage/local/include/linbox/matrix/matrixdomain/blas-matrix-domain.h:51:
In file included from /Users/admin/sage/local/include/linbox/matrix/dense-matrix.h:79:
In file included from /Users/admin/sage/local/include/linbox/matrix/densematrix/blas-matrix.h:44:
/Users/admin/sage/local/include/linbox/vector/blas-vector.h:306:38: error: member reference base type 'const long'
      is not a structure or union
                        _size(V.size()),_1stride(1),_rep(V.size(), F.zero),_ptr(&_rep[0]),_field(&F)
                                                         ~^~~~~
/Users/admin/sage/local/include/linbox/vector/blas-vector.h:306:61: warning: field '_rep' is uninitialized when used
      here [-Wuninitialized]
                        _size(V.size()),_1stride(1),_rep(V.size(), F.zero),_ptr(&_rep[0]),_field(&F)
                                                                                 ^
/Users/admin/sage/local/include/linbox/vector/blas-vector.h:129:13: error: type 'long' cannot be used prior to '::'
      because it has no members
                        typename OtherVector::const_iterator jt = V.begin();
                                 ^
/Users/admin/sage/local/include/linbox/vector/blas-vector.h:311:4: note: in instantiation of function template
      specialization 'LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::__1::vector<Givaro::Integer,
      std::__1::allocator<Givaro::Integer> > >::createBlasVector<long>' requested here
                        createBlasVector(V);
                        ^
main.cpp:8:15: note: in instantiation of function template specialization
      'LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::__1::vector<Givaro::Integer,
      std::__1::allocator<Givaro::Integer> > >::BlasVector<long>' requested here
    res = new LinBox::DenseVector<Givaro::ZRing<Givaro::Integer>>(zz, nbcols);
              ^
1 warning and 3 errors generated.
```

This error was first encountered in sagemath development, ticket [#23214#comment:26](https://trac.sagemath.org/ticket/23214#comment:26)

**Comment by pascalgiorgi** [comment]
The compilation error is coming from some specific code according to either gcc or osx environment in blas-vector. More generally, the handling of the size parameter in blas-vector is weird.

In particular, we have these two definitions 

#ifdef __GNUC__
#ifndef __x86_64__
#if (__GNUC__ == 4 && __GNUC_MINOR__ ==4 && __GNUC_PATCHLEVEL__==5)
		BlasVector (const _Field &F, const long &m, const Element e=Element()) :
			Father_t(),
			_size((uint32_t)m),_1stride(1),_rep(_size, e),_ptr(_rep.data()),_field(&F)
		{
			// Father_t is garbage until then:
			setIterators();

			linbox_check(_size==0 || _ptr != NULL);
		}
#endif
#endif
#endif

#if defined(__APPLE__) || (defined(__s390__) && !defined(__s390x__))
		BlasVector (const _Field &F, const unsigned long &m, const Element e=Element())  :
			Father_t(),
			_size((uint32_t)m),_1stride(1),_rep(_size, e),_ptr(_rep.data()),_field(&F)
		{
			// Father_t is garbage until then:
			setIterators();

			linbox_check(_size==0 || _ptr != NULL);

			// linbox_check(_size >= this->begin()->_stride); PG -> do not understand
		}

#endif

I do not see any reasons why we have added these two constructors from either long or unsigned long with an explicit cast to uint32_t when the underlying attribute is a size_t (maybe SAGE compatibility ?)
From my opinion, we should only provide a constructor from a size_t and let the cast do the rest.
For instance, it is non sense to allow a multi precision integer to be given as the size of the vector.

If no one has a good reason I propose  to remove all these constructors.

**Comment by ClementPernet** [comment]
Agreed. I tried to remove all these unecessary constructors and only left 
```
BlasVector(const Field&F, const size_t& n, const Element e=Element())
```
Surprisingly, this still fails with the same error message, indicating, that the compiler jumps to the second constructor considering `long` as a template parameter `VectorBase` , not even trying to cast it into a size_t and use the first constructor. I can't explain why especially since I can not reproduce this problem on the simple equivalent code below (which compiles fine on osx):
```
#include <stdlib.h>
class A{
    int x;
    int y;
};

template<class T>
class B{
public:
    B (const T& t, const size_t& x) {_b=x+1;_a=t;}
    
    template<class U>
    B (const T& t, const U& u){_b=0; _a=t;}
private:
    size_t _b;
    T _a;
};

int main(int argc, char**argv){
    long x=atoi(argv[1]);
    A a;
    B<A>* b;
    b=new B<A>(a, x);
}
```
For the moment I see 2 workarounds:
 - Enforce the requirement that all dimensions and indices in LinBox must be `size_t` and not `long`. 
Normally these 2 types rather have smooth conversions, but OSX has produced numerous similar issues because size_t is not typedefed to unsigned long.
In the sage ticket, where this issue originates from https://trac.sagemath.org/ticket/23214 this means either casting a.ncols into a size_t before constructing the vector, or changing the type of matrix/vector dimensions from long to size_t.
 - remove LinBox's BlasVector templated constructor 
```template<class VectorBase>
BlasVector(const Field&F, const VectorBase& V))
```
It is used only once in the library, and this call could easily be replace by a call without the first argument. It is a no brainer to do this change, but I'm still annoyed to have to fix this issue this way.
