### ISSUE TITLE
Givaro::Modular<uint32_t,uint64_t> sparse rank test suite (0.014662 s) 255

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/linbox#14]
nehalem + broadwell : test-rank-u32
----
Givaro::Modular<uint32_t,uint64_t> sparse rank test suite (0.014662 s)
255
----
ERROR : rank are not equal 
sparse elim rank 13
blackbox rank 13
Blas elimination rank 12
----

**Comment by ClementPernet** [comment]
Modular<unsigne type> should not be used in FFLAS-FFPACK, as it will ultimately compute negative numbers, thus adding 2^64 mutliples to the result.
We should decide where to prevent such calls, or whether fflas should have a special treatment for them.

**Comment by bdsaunders** [comment]
OK.  now test-rank won't try blas elim unless is_signed
