### ISSUE TITLE
row index: unsigned long versus size_t

### ISSUE THREAD

**Issue by videlec** [linbox-team/linbox#144]
The function `InPlaceLinearPivoting` from `linbox/algorithms/gauss.h` (line 227) is declared as follows
```
template <class _Matrix>                                      
unsigned long& InPlaceLinearPivoting(unsigned long &rank,
                                     Element& determinant,
                                     _Matrix        &A,
                                     unsigned long Ni,
                                     unsigned long Nj) const;
```
I would have expected all of `rank`, `Ni` and `Nj` to be `size_t` rather than `unsigned long` as they stand for row/column size.

This is particularly annoying when `size_t` is `unsigned long long` and not `unsigned long` (this is the case on standard 32 bits Linux).

Downstream ticket in SageMath: [#23214](https://trac.sagemath.org/ticket/23214).

**Comment by bdsaunders** [comment]
I agree that these should be size_t.
