### ISSUE TITLE
test-givarozpz broken with fieldArchetype<Modular<int16> >

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#16]
gdb stack after segfault:

#0  0x000000000043fef9 in Givaro::Modular<short, short>::assign (this=0x79a698, r=@0x8: <error reading variable>, a=@0x7a6b48: 0)
    at /home/pernet/Logiciels/Builds/include/givaro/modular-int16.inl:391
#1  0x0000000000484ef9 in LinBox::FieldEnvelope<Givaro::Modular<short, short> >::assign (this=0x79a690, x=..., y=...) at ../linbox/field/envelope.h:182
#2  0x000000000041258d in LinBox::FieldArchetype::assign (this=0x7fffffffd6e0, x=..., y=...) at ../linbox/field/archetype.h:230
#3  0x0000000000434aa3 in testRing<LinBox::FieldArchetype> (F=..., title=0x486cc0 "Testing archetype with envelope of Givaro::Modular< int16_t> field", fieldp=true, 
    runInitConvertIdentity=true) at test-field.h:141
#4  0x0000000000418ef4 in testField<LinBox::FieldArchetype> (F=..., title=0x486cc0 "Testing archetype with envelope of Givaro::Modular< int16_t> field", fieldp=true, 
    runInitConvertIdentity=true) at test-field.h:417
#5  0x000000000040b014 in main (argc=1, argv=0x7fffffffde88) at test-givaro-zpz.C:138

**Comment by jgdumas** [comment]
elements must be initialized !
