### ISSUE TITLE
[Question] Calculating a nullspace basis

### ISSUE THREAD

**Issue by tjclement** [linbox-team/linbox#176]
Thank you for developing and maintaining this cool library. I am hoping to use linbox to calculate an exact basis of the (right) null space of a matrix of several hundred rows and columns of (possibly large) integers. Some matrices in my problem are dense, some are sparse.

I've seen examples/nullspace.C, and it looks like what I need, but I must admit that I'm a bit lost regarding which field or ring to use. Any pointers in the right direction would be much appreciated, thanks.

**Comment by Breush** [comment]
Hello @tjclement, are your computations done over the integers?
If so, you'll need a `Givaro::ZRing<LinBox::Integer>` as your ring.

You might want to take a look at `tests/test-nullspace.C`.

Let me know if you need some more help.

**Comment by tjclement** [comment]
Thanks for your answer! It seems I had forgotten to reply, my apologies. Indeed my computations are done over the integers, and your comment was very helpful in getting a working setup; thank you.
