### ISSUE TITLE
polynomial matrix FFT assumes SIMD 128 instructions are always present

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#22]
test-order-basis triggers many errors on powerpc (power8) as (e.g.) no __m128i type is available.
SIMD dependent code should be protected within proper #ifdefs as in fflas-ffpack.

make test-order-basis
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../linbox -I/include -DLinBoxTestOnly -O0 -Wall -g -DNDEBUG -U_LB_DEBUG -g -DNDEBUG -U_LB_DEBUG     -fopenmp -I/home/cper\
net/builds/include -D__FFLASFFPACK_HAVE_CBLAS -fabi-version=6 -I/home/cpernet/builds/include -I/home/cpernet/builds/include -DFFLAS_COMPILED -DFFPACK_COMPILED\
    -I/home/cpernet/builds/include -D__FFLASFFPACK_HAVE_CBLAS -fabi-version=6 -I/home/cpernet/builds/include -I/home/cpernet/builds/include -DFFLAS_COMPILED -\
DFFPACK_COMPILED  -std=gnu++11  -c -o test-order-basis.o test-order-basis.C
In file included from ../linbox/algorithms/polynomial-matrix/polynomial-fft-transform.h:33:0,
                 from ../linbox/algorithms/polynomial-matrix/matpoly-mult-fft-wordsize-fast.inl:34,
                 from ../linbox/algorithms/polynomial-matrix/matpoly-mult-fft.h:116,
                 from ../linbox/algorithms/polynomial-matrix/polynomial-matrix-domain.h:35,
                 from test-order-basis.C:9:
../linbox/algorithms/polynomial-matrix/simd.h:142:9: error: '__m128i' does not name a type
 typedef __m128i  _vect128_t;
         ^
In file included from ../linbox/algorithms/polynomial-matrix/matpoly-mult-fft-wordsize-fast.inl:34:0,
                 from ../linbox/algorithms/polynomial-matrix/matpoly-mult-fft.h:116,
                 from ../linbox/algorithms/polynomial-matrix/polynomial-matrix-domain.h:35,
                 from test-order-basis.C:9:
../linbox/algorithms/polynomial-matrix/polynomial-fft-transform.h:262:47: error: '__m128i' does not name a type
   inline void reduce128_modp(uint32_t*, const __m128i&);
                                               ^
../linbox/algorithms/polynomial-matrix/polynomial-fft-transform.h:263:127: error: '__m128i' does not name a type
   inline void Butterfly_DIF_mod2p_4x1_SSE(uint32_t* ABCD, uint32_t* EFGH,const uint32_t* alpha, const uint32_t* alphap, const __m128i& P, const __m128i& P2);
 
....

**Comment by ClementPernet** [comment]
Fixed in feff961648bbd564e38ab5c265ff9db302355c51

**Comment by ClementPernet** [comment]
The problem re-appeared.
compiling benchmark-order-basis.C
on a machine with no sse (ppc64).
This is reproducible on any arch, but configuring fflas-ffpack with `--disable-sse`.

Also, I just realized that I erroneously mentionned feff961 for its resolution.
Pascal, Romain ?

**Comment by romainlebreton** [comment]
It should be fixed in https://github.com/linbox-team/linbox/commit/f9d53ebbbdeb09cf6b5ff0db07c1fe0b69a1146e
