### ISSUE TITLE
Problems with polynomial matrix multiplication

### ISSUE THREAD

**Issue by vneiger** [linbox-team/linbox#240]
While trying to write a basic kernel basis algorithm for polynomial matrices, I am struggling with polynomial matrix multiplication.

Two examples are attached.
- In the first, we multiply two matrices that are 1 x 2 and 2 x 1, of degree 3, and whose product is zero (base field is a prime field with the FFT prime 699089), easily checked for example with Sagemath. But I get a nonzero product using the code in this example.
- In the second, we multiply two matrices, one of which has its size attribute which is not directly related to its actual degree; such situations happen naturally in kernel algorithms. Again, this fails to compute the right product, as one can observe just looking at the degrees (as done in the example file). Note: the first example indicates that the fact that this second example fails may well be completely unrelated to the fact that the size is not the actual size.

Thanks for help.

[polmatmul.tar.gz](https://github.com/linbox-team/linbox/files/3974361/polmatmul.tar.gz)

**Comment by vneiger** [comment]
In the meantime, the first issue has been fixed. However, the second one remains, as far as I understand. Here is the corresponding test file with the new polynomial matrix interface.
[test_pmmul2.zip](https://github.com/linbox-team/linbox/files/9055866/test_pmmul2.zip)

**Comment by pascalgiorgi** [comment]
it seems that there is a bug in your code. The matrix dimensions of the product is set to 4x4 while it should be 2x2.
I corrected the file and it works fine to me. I attached it to this thread.
[test_pmmul2.C.zip](https://github.com/linbox-team/linbox/files/9070682/test_pmmul2.C.zip)

**Comment by vneiger** [comment]
Yes, this made no sense indeed, sorry for the mistake. Your corrected code works as expected, and the other issue (first one in the original post) has been fixed. We can close this issue.
