### ISSUE TITLE
Fatal warning during installation: givaro/givconfig.h - no such file or directory

### ISSUE THREAD

**Issue by HereAround** [linbox-team/linbox#244]
I am trying to install linbox on Ubuntu18.04. Unfortunately, I receipt several warning about givaro/givconfig.h not being present. How can I resolve this?

Explicitly, I use this git-repository (I am at commit 553ba4893d058ead1bc5bd1d161349433200d5bd from 19/12/2019) and have followed the instructions at https://linalg.org/linbox-html/install-dist.html for the installation. I have thus issued the linbox-auto-install.sh with the following options:

./linbox-auto-install.sh --prefix=/my-lib-folder --enable-openblas=y --enable-blis=y --enable-gmp=y --enable-check=y --enable-optimization=y --enable-drivers=y

where 'my-lib-folder' my chosen folder for the libraries. This script finishes by reminding me to issue "
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:my-lib-folder'". However, it also issues a critical warning just before that:

../../linbox/integer.h:44:10: fatal error: givaro/givconfig.h: No such file or directory
 #include <givaro/givconfig.h>

In my case, this file is located in three locations:
- /linbox/build/givaro/src/kernel/system/givconfig.h
- my-lib-folder/include/givaro/givconfig.h
- in my Sage installation

I have issued "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:my-lib-folder" hoping that then, the file my-lib-folder/include/givaro/givconfig.h would be found. However, if I now issue "make", then the same warning appears again and make finishes by

Makefile:601: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

I have also issued "make check". Here is its summary:
- TOTAL: 35
- PASS:  35
- SKIP:  0
- XFAIL: 0
- FAIL:  0
- XPASS: 0
- ERROR: 0

Below this printout, however, again the above warning is being raised and it finishes by

Makefile:601: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

For completeness, here is the output of make fullcheck:

./checker
test-bitonic-sort                  build OK, run OK.  
test-blackbox-block-container      build OK, run OK.  
test-blas-domain                   build OK, run OK.  
test-blas-matrix                   build OK, run OK.  
test-block-wiedemann               build OK, run OK.  
test-butterfly                     build OK, run OK.  
test-charpoly                      build OK, run OK.  
test-commentator                   build OK, run OK.  
test-companion                     build OK, run OK.  
test-cra                           build OK, run OK.  
test-cradomain                     build OK, run FAIL
test-dense                         build OK, run OK.  
test-dense-zero-one                skipped, half baked, bds responsible
test-det                           build OK, run OK.  
test-diagonal                      build OK, run OK.  
test-dif                           build OK, run OK.  
test-direct-sum                    build OK, run OK.  
test-dyadic-to-rational            build OK, run OK.  
test-echelon-form                  build OK, run OK.  
test-ffpack                        build OK, run OK.  
test-fft                           build OK, run OK.  
test-fibb                          build OK, run OK.  incomplete
test-frobenius                     build OK, run OK.  
test-frobenius-large               skipped, NTL not present
test-frobenius-small               skipped, NTL not present
test-getentry                      build OK, run OK.  
test-gf2                           build OK, run OK.  
test-givaro-interfaces             build OK, run OK.  
test-givaropoly                    build OK, run OK.  
test-givaro-zpz                    build OK, run OK.  
test-givaro-zpzuns                 build OK, run OK.  
test-gmp-rational                  build OK, run OK.  
test-hadamard-bound                build OK, run OK.  
test-hilbert                       build OK, run OK.  
test-hom                           build OK, run OK.  
test-invariant-factors             skipped, NTL not present
test-inverse                       build OK, run OK.  
test-isposdef                      build OK, run OK.  
test-ispossemidef                  build OK, run OK.  
test-last-invariant-factor         build OK, run OK.  
test-local-smith-form-sparseelim   build OK, run OK.  
test-matpoly-mult                  build OK, run OK.  
test-matrix-domain                 build OK, run OK.  
test-matrix-stream                 build OK, run OK.  
test-minpoly                       build OK, run FAIL
test-modular-balanced-double       build OK, run OK.  
test-modular-balanced-float        build OK, run OK.  
test-modular-balanced-int          build OK, run OK.  
test-modular-double                build OK, run OK.  
test-modular-float                 build OK, run OK.  
test-modular-int                   build OK, run OK.  
test-moore-penrose                 build OK, run OK.  
test-mpi-comm                      skipped, MPI not present
test-ntl-hankel                    skipped, NTL not present
test-ntl-lzz_p                     skipped, NTL not present
test-ntl-lzz_pe                    skipped, NTL not present
test-ntl-lzz_pex                   skipped, NTL not present
test-ntl-lzz_px                    skipped, NTL not present
test-ntl-rr                        skipped, NTL not present
test-ntl-sylvester                 skipped, NTL not present
test-ntl-toeplitz                  skipped, NTL not present
test-ntl-zz_p                      skipped, NTL not present
test-nullspace                     build OK, run OK.  
test-one-invariant-factor          build OK, run FAILprobalistic algorithm, sometimes fails
test-opencl-domain                 skipped, OpenCL not present
test-optimization                  skipped, not unit/regression test conforming
test-order-basis                   build OK, run OK.  
test-param-fuzzy                   build OK, run OK.  Noncompliant field
test-permutation                   build OK, run OK.  
test-plain-domain                  build OK, run OK.  
test-poly-det                      skipped, incomplete test (if still relevant)
test-polynomial-ring               build OK, run OK.  
test-qlup                          build OK, run OK.  
test-quad-matrix                   skipped, half baked, bds responsible
test-randiter-nonzero-prime        build OK, run OK.  
test-random-matrix                 build OK, run OK.  
[PASS]: data/rk9_7_10.sms rank 10
[PASS]: data/rk9_7_10.sms rank 9 mod 7
test-rank-ex                       build OK, run OK.  
test-rank-Int                      build OK, run OK.  
test-rank-md                       build OK, run OK.  
test-rank-u32                      build OK, run OK.  
test-rat-charpoly                  skipped, stale test. solns over QQ need fresh tests
test-rational-matrix-factory       build OK, run OK.  
test-rational-reconstruction-base  build OK, run OK.  
test-rational-solver-adaptive      build OK, run OK.  
test-rational-solver               build OK, run OK.  
test-rat-minpoly                   skipped, stale test. solns over QQ need fresh tests
test-rat-solve                     skipped, infinite loop
test-regression2                   build OK, run OK.  
test-regression                    build OK, run OK.  
test-scalar-matrix                 build OK, run OK.  
test-serialization                 build OK, run OK.  
test-smith-form-adaptive           build OK, run OK.  
test-smith-form-binary             build OK, run FAIL
test-smith-form                    build OK, run OK.  
test-smith-form-iliopoulos         build OK, run OK.  
test-smith-form-local              build OK, run OK.  
Expected smith form SL: {{1,8}{1440000,1}{0,2}}
Computed Smith form SL: {{1,8}{1440000,1}{0,2}}
PASSED.
Expected smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1440000, 0, 0]
Computed Smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1440000, 0, 0]
PASSED.
Expected smith form SL: {{1,23}{10,1}{1560,1}}
Computed Smith form SL: {{1,23}{10,1}{1560,1}}
PASSED.
Expected smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 1560]
Computed Smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 1560]
PASSED.
Expected smith form SL: {{1,22}{2,1}{66,2}{198,1}{15444,1}{0,3}}
Computed Smith form SL: {{1,22}{2,1}{66,2}{198,1}{15444,1}{0,3}}
PASSED.
Expected smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 66, 66, 198, 15444, 0, 0, 0]
Computed Smith form: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 66, 66, 198, 15444, 0, 0, 0]
PASSED.
test-smith-form-valence            build OK, run OK.  
test-solve                         build OK, run OK.  most of the tests are commented out
test-solve-full                    build OK, run OK.  
test-solve-nonsingular             build OK, run OK.  
test-sparse                        build OK, run OK.  
test-sparse-map-map                skipped, const issue in givranditer, curious use of nonexistant next() in Extension
test-subiterator                   build OK, run OK.  
test-submatrix                     build OK, run OK.  
test-subvector                     build OK, run OK.  
test-sum                           build OK, run OK.  
test-toeplitz                      skipped, NTL not present
test-toeplitz-det                  skipped, NTL not present
test-toom-cook                     build OK, run OK.  one method does not work
test-trace                         build OK, run OK.  
test-transpose                     build OK, run OK.  
test-triplesbb                     build OK, run OK.  
test-triplesbb-omp                 build OK, run OK.  
test-tutorial                      build OK, run OK.  
test-vector-domain                 build OK, run OK.  
test-weak-popov-form               skipped, NTL not present
test-zero-one                      build OK, run OK.  
--------------------------------------------------------------------
Of 117 tests, 88 passed, 0 failed to compile, 4 failed at runtime,  and 25 were skipped.
--------------------------------------------------------------------
Makefile:3221: recipe for target 'fullcheck' failed
make[1]: *** [fullcheck] Error 255
make[1]: Leaving directory '/home/i/HDD/Computer/Mathematics_software/linbox/tests'
Makefile:1030: recipe for target 'fullcheck' failed
make: *** [fullcheck] Error 2

**Comment by HereAround** [comment]
Allow me to add more details to my attempt to install a running version of linbox.

https://ci.inria.fr/linbox/job/LinBox/ tells me that the latest build fails. Maybe because of the above?

I have thus tried the latest stable version according to jenkins:
- git reset --hard cd24ff6fc35b40d4c67a8e998058eb893d32849e
- ./linbox-auto-install.sh...
This leads to exactly the same issue as reported above.

I have even tried version 1.3.2 (2012), which I downloaded from https://linalg.org/download.html and installed the latest givaro (without issues) from https://github.com/linbox-team/givaro. Still, I cannot configure with old version of linbox. I issued:

./configure script --with-givaro =/path/to/givaro

Surprisingly, the script complains that my givaro version is too old and cannot be found.

Any suggestions on how I can have a running version of linbox are very much appreciated.

**Comment by jgdumas** [comment]
Hello, sorry cannot reproduce that one.
Can you post (or send me the 'linbox-auto-install.log' ?

**Comment by HereAround** [comment]
By now, I have installed linbox from the sources, i.e. without using the linbox-auto-install.sh.

Still, for your convenience, I have just reproduced the above error once more. I send you the log by email.

**Comment by jgdumas** [comment]
OK. This is some errors in the drivers for Maple in the interfaces/driver directory.
If you are not using Maple everything should be fine (just remove the '--enable-drivers=y' option).
I flag this as a prolem in these drivers.
