### ISSUE TITLE
Bashism in MPI configure check

### ISSUE THREAD

**Issue by orlitzky** [linbox-team/linbox#251]
In https://github.com/linbox-team/linbox/blob/master/macros/mpi-check.m4#L41 there's a test,

```m4
    AS_IF([ test "x$with_mpi" == "xyes" ],
```

The double-equals operator is a bash-only thing, and the configure script should work in any POSIX shell. With Dash, for example, that check always produces an error. The fix is simple; just delete one of the equals signs:

```m4
    AS_IF([ test "x$with_mpi" = "xyes" ],
```

**Comment by ClementPernet** [comment]
Thanks for the report. I just pushed the trivial fix directly to master in 9e12c2d .
