### ISSUE TITLE
Minor compilation issues

### ISSUE THREAD

**Issue by jamesjer** [linbox-team/linbox#26]
While building linbox 1.4.0 for the upcoming Fedora 24 release, gcc complained about a few code constructs, namely:
- In linbox/algorithms/one-invariant-factor.h, setCrossover() contains the statement "if(0 <= t <= 1) ...", which would be nice, but C++ doesn't actually support that syntax.  It should be replaced with "if(0 <= t && t <= 1) ...".
- In both linbox/matrix/sparsematrix/sparse-tpl-matrix.inl (line 124) and linbox/matrix/sparsematrix/sparse-tpl-matrix-omp.inl (line 217), there is an operator= with a return statement that doesn't return anything.  Those should return *this.

**Comment by bdsaunders** [comment]
Thanks for that.  I've patched those things in the repository.  Thus fixed
when 1.4.1 comes out.

In the case of the sparse-tpl-matrix, I've just removed the assignment
operators altogether, as that is not part of our sparse matrix interface.
