### ISSUE TITLE
allPos used in isPosSemiDef

### ISSUE THREAD

**Issue by orlitzky** [linbox-team/linbox#261]
I was  just casually reading this and have no idea what's going on, but: shouldn't that be `allNonNeg`, for a semidefinite test?

https://github.com/linbox-team/linbox/blob/4e35dd832a3e7f3a37b040b4b60d2726c5d980a1/linbox/algorithms/signature.h#L178

**Comment by bdsaunders** [comment]
At that point in the code, it is a maximal nonsingular principal minor that
is being checked.  So allPos is wanted there.

**Comment by orlitzky** [comment]
Sorry for the scare then =)
