### ISSUE TITLE
Empty programs directory causes compilation failure

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#267]
Looks like, the smith directory is missing in linbox/programs.

**Comment by jgdumas** [comment]
Cannot reproduce it.
when I clone I do have the directory, right only with a Makefile.am ...
Maybe for some reason you need the makefile ? (then use https://github.com/linbox-team/linbox/tree/prgsmith)

**Comment by ClementPernet** [comment]
Well, because I commented out the mentions to programs/smith in configure.ac in f02389b 
waiting for you to push the smith directory !

**Comment by ClementPernet** [comment]
Fixed in f02389b and moved the preliminary program directory in the PR #270
