### ISSUE TITLE
Master not compiling with OpenCL installed

### ISSUE THREAD

**Issue by rolfvdhulst** [linbox-team/linbox#275]
PR #250 changed most of the template arguments to the BlasMatrixDomain classes, but it seems that a few were missed. I get errors in linbox/matrix/matrixdomain/opencl-domain.inl

In particular, when compiling a non-stable version (using the latest master of givaro and fflas-ffpack), I get errors (see file below:). Most are probably easy to fix , looking at the PR.
[linboxerror.txt](https://github.com/linbox-team/linbox/files/6591294/linboxerror.txt)

**Comment by rolfvdhulst** [comment]
Disabling OpenCL compilation by adding --without-opencl --without-ocl was a workaround for me (for now).

**Comment by ClementPernet** [comment]
Fixed by #287
