### ISSUE TITLE
all tests and benchmark compilation fails with clang

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#29]
@romainlebreton : since your last merge.
See [here](https://ci.inria.fr/linbox/job/FFLAS-FFPACK-clang++/label=linbox-ubuntu-amd64/71/PerfPublisher/testDetails.benchmark-fgemm/)

**Comment by romainlebreton** [comment]
@ClementPernet Fixed. Sorry for the inconvenience.

**Comment by ClementPernet** [comment]
Still failing with clang, on OSX:
[see here](https://ci.inria.fr/linbox/job/FFLAS-FFPACK-clang++/label=linbox-osx-amd64/72/PerfPublisher/)

**Comment by ClementPernet** [comment]
Apologies: this is an issue with fflas-ffpack, not linbox. i'm moving it there: this is [issue #26](https://github.com/linbox-team/fflas-ffpack/issues/26)
