### ISSUE TITLE
Black-box charpoly is broken

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#3]
Memory issues in the algorithm/bbcharpoly.h causing failure of test-charpoly.

Blackbox method temporarily default to dense methods waiting for this bug to be fixed

**Comment by bdsaunders** [comment]
I think there is some small prime issue and/or CRA issue.  test-cra is broken and test-rat-charpoly goes into an infinite loop of computing modular cases.

**Comment by ClementPernet** [comment]
You probably hit the same bug as I did last week. It was a bug in Givaro, so updating your givaro install should fix it. Do you confirm?

**Comment by bdsaunders** [comment]
In my environment,
686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
, test-charpoly fails to compile.  Here is the first error:

/usa/saunders/sandbox/include/givaro/zring.h: In instantiation of ‘Givaro::ZRing<_E
lement>::Element& Givaro::ZRing<_Element>::init(Givaro::ZRing<_Element>::Element&, 
const T&) const [with T = long int; _Element = Givaro::Integer; Givaro::ZRing<_Elem
ent>::Element = Givaro::Integer]’:
test-charpoly.C:117:2:   required from ‘bool testIdentityCharpoly(Dom&, size_t, boo
l) [with Dom = Givaro::ZRing<Givaro::Integer>; size_t = unsigned int]’
test-charpoly.C:334:34:   required from here
/usa/saunders/sandbox/include/givaro/zring.h:174:20: error: conversion from ‘const 
long int’ to ‘const Element {aka const Givaro::Integer}’ is ambiguous
         { return x = static_cast<const Element&>(s); }
                    ^
Then test-rat-charpoly compiles but goes into an infinite loop:

zebra:~/sandbox/linbox/tests> test-rat-charpoly rep|more
Writing report data to rep

Rational solve test suite...
  Testing rational charpoly of diagonal matrix ...
    Iteration 0...
      Rational Charpoly...
        Givaro::Modular Dense Charpoly ...
                done (0.0010239 s)
        Givaro::Modular Dense Charpoly ...
                done (0.000878913 s)
        Givaro::Modular Dense Charpoly ...
                done (0.000845928 s)
        Givaro::Modular Dense Charpoly ...
                done (0.00085611 s)
        Givaro::Modular Dense Charpoly ...
                done (0.00077389 s)
...

**Comment by bdsaunders** [comment]
btw,  test-rat-charpoly had the infinite loop already before, when the modular steps were blackbox rather than elim.

**Comment by ClementPernet** [comment]
Ok, I assume this is a 32 bit machine, nice catch!
I changed the -2L constant into a -2_i64 in test-charpoly.C Does this fix the compile issue (I don't have a 32 bit machine handy).
As for test-rat-charpoly, I did not notice this bug as it is not in the basic test list. I have no clue about the status of rationals and CRT in LinBox. JG, has anyone worked on it after Ana?

**Comment by bdsaunders** [comment]
Works.

**Comment by ClementPernet** [comment]
Wait, no. As I mentionned in the description of this issue, the code at fault has been unabled, waiting for it to be fixed. So let's keep this issue open as a reminder.
