### ISSUE TITLE
bench-new-fft.C fails to compile

### ISSUE THREAD

**Issue by BastienVialla** [linbox-team/linbox#30]
Hey, 

bench-new-fft.C fails to compile on osx with SSE, AVX, but no AVX2.

[error_log.txt](https://github.com/linbox-team/linbox/files/300107/log.txt)

@romainlebreton @pascalgiorgi

**Comment by romainlebreton** [comment]
@BastienVialla Please check if https://github.com/linbox-team/linbox/commit/45460232fa9a547d00fe3c70f6e1d0fcf5e927c9 solves your issue. Thanks for reporting it !

**Comment by BastienVialla** [comment]
@romainlebreton https://github.com/linbox-team/linbox/commit/45460232fa9a547d00fe3c70f6e1d0fcf5e927c9 solves the issue. Thanks.
