### ISSUE TITLE
LinBox does not compile

### ISSUE THREAD

**Issue by BastienVialla** [linbox-team/linbox#32]
Hey, 

During compilation, the diophantine-solver does not compile due to igemm and SIMD.

I compiled the master branch with g++6 on osx-ivybridge (SSE4.1, AVX) and --disable-openmp.

It seems that problem come from the new SIMD flags.

[log_linbox.txt](https://github.com/linbox-team/linbox/files/391024/log_linbox.txt)

@ClementPernet @romainlebreton

**Comment by romainlebreton** [comment]
Hopefully, commit 0a6c5ec00904d991fd0d6cada49582650ec6f6f7 has corrected it. @BastienVialla Can you please check ?
BTW, it was a fflas-ffpack issue, not linbox.

**Comment by BastienVialla** [comment]
Thx, LinBox compiles, but test-det.C still doesn't. It seems to be an always_inline problem in simd256<float>.

Do you want me to move the issue to fflas ?

[log_linbox.txt](https://github.com/linbox-team/linbox/files/391186/log_linbox.txt)

**Comment by romainlebreton** [comment]
No, let's finish this issue here.
I don't know this errors. It works fine on my computer. I guess it is related to the use of g++6.
@ClementPernet  Are we suppose to support g++6 yet ?
@BastienVialla Can you try with g++5 ?

**Comment by ClementPernet** [comment]
Yes we are supporting gcc-6.
On our build farm, however, we do not have gcc-6 on osx, but only clang and the gcc front-end of clang (we should configure a true gcc there though).

Are you sure that the -mavx2 option is passed to the compiler?

**Comment by romainlebreton** [comment]
He has only AVX on his machine.

**Comment by BastienVialla** [comment]
I don't have AVX2 on my computer.
However,  -mavx is not passed to the compiler: 
g++ -DHAVE_CONFIG_H -I. -I..  -DLinBoxTestOnly -O2 -Wall -g -DNDEBUG -U_LB_DEBUG -g -DNDEBUG -U_LB_DEBUG -I../linbox -I/Users/vialla/work/lib/fflas-ffpack/ -I/Users/vialla/work/lib/build//include -I/Users/vialla/work/lib/build//include   -I/Users/vialla/work/lib/build//include   -O3 -c -o test-det.o test-det.C

**Comment by ClementPernet** [comment]
Strange, LinBox should get all the -mavx -msse ... flags from givaro.pc and fflas-ffpack.pc file where they have been detected.
@BastienVialla can you make sure that you don't have an old .pc file in the way that does not include those flags?
Or just make sure that you have added to your PKG_CONFIG_PATH the value `<install_dir>/lib/pkg_config` .

**Comment by ClementPernet** [comment]
Fyi, LinBox now compiles on all our CI targets:https://ci.inria.fr/linbox/view/LinBox%20ecosystem/job/LinBox/111/

**Comment by romainlebreton** [comment]
Yeah !!!

**Comment by BastienVialla** [comment]
Indeed, it was an old .pc file.
After reconfiguring et recompiling everything, all tests passed ;)
