### ISSUE TITLE
rns in smith

### ISSUE THREAD

**Issue by bdsaunders** [linbox-team/linbox#64]
In test-smith-form-adaptive and test-smith-form-binary we get this error message:

ERROR (at init in /usa/saunders/sandbox/include/fflas-ffpack/field/rns-double.inl:42): 
Precondition not met:rns_struct: init (too large entry)
k=4 _ldm=1

...but the test passes.  I'm guessing the error is caught and a workaround launched.  Since there is no error at user level, can we suppress the error message, please.

**Comment by jgdumas** [comment]
OK, you are calling a multiplication with a Zero matrix and we are not handling this case.
I look at it ...

**Comment by jgdumas** [comment]
OK, solved. No need to multiply zero matrices
