### ISSUE TITLE
Master Branch Does Not Compile

### ISSUE THREAD

**Issue by gmh33** [linbox-team/linbox#65]
The file linbox/algorithms/block-massey-domain.h still relies on the old sigma-basis.h file, and causes the project to not compile.  Adding that file and the old matpoly-mult.h back causes a conflict with the new polynomial matrix code.

**Comment by gmh33** [comment]
I pushed a temporary solution (re-adding files and renaming class to avoid conflict), but this will need a more permanent solution.

**Comment by pascalgiorgi** [comment]
I fixed the issue by retrieving all the old files related to the sigma-basis.h code.
The update with newer code will be done on the branch "block-wiedemann" before merging with the master and removing old code.
