### ISSUE TITLE
order basis macros multiply defined with different values

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/linbox#66]
In file included from ../linbox/algorithms/polynomial-matrix/order-basis.h:38:0,
                 from ../linbox/blackbox/block-hankel-inverse.h:35,
                 from ../linbox/algorithms/lifting-container.h:47,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/polynomial-matrix/polynomial-matrix-domain.h:30:0: warning: "KARA_DEG_THRESHOLD" redefined
 #define KARA_DEG_THRESHOLD  2
 
In file included from ../linbox/algorithms/sigma-basis.h:40:0,
                 from ../linbox/algorithms/block-massey-domain.h:43,
                 from ../linbox/algorithms/lifting-container.h:43,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/matpoly-mult.h:46:0: note: this is the location of the previous definition
 #define KARA_DEG_THRESHOLD  1
 
In file included from ../linbox/algorithms/polynomial-matrix/order-basis.h:38:0,
                 from ../linbox/blackbox/block-hankel-inverse.h:35,
                 from ../linbox/algorithms/lifting-container.h:47,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/polynomial-matrix/polynomial-matrix-domain.h:31:0: warning: "FFT_DEG_THRESHOLD" redefined
 #define FFT_DEG_THRESHOLD   2
 
In file included from ../linbox/algorithms/sigma-basis.h:40:0,
                 from ../linbox/algorithms/block-massey-domain.h:43,
                 from ../linbox/algorithms/lifting-container.h:43,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/matpoly-mult.h:45:0: note: this is the location of the previous definition
 #define FFT_DEG_THRESHOLD   64
 
In file included from ../linbox/blackbox/block-hankel-inverse.h:35:0,
                 from ../linbox/algorithms/lifting-container.h:47,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/polynomial-matrix/order-basis.h:45:0: warning: "MBASIS_THRESHOLD" redefined
 #define MBASIS_THRESHOLD (1<<MBASIS_THRESHOLD_LOG)
 
In file included from ../linbox/algorithms/block-massey-domain.h:43:0,
                 from ../linbox/algorithms/lifting-container.h:43,
                 from ../linbox/algorithms/rational-solver.inl:37,
                 from ../linbox/algorithms/rational-solver.h:1045,
                 from ../linbox/algorithms/hybrid-det.h:35,
                 from ../linbox/solutions/det.h:602,
                 from ../linbox/algorithms/bbcharpoly.h:46,
                 from ../linbox/solutions/charpoly.h:35,
                 from test-charpoly.C:46:
../linbox/algorithms/sigma-basis.h:51:0: note: this is the location of the previous definition
 #define MBASIS_THRESHOLD 16

**Comment by pascalgiorgi** [comment]
closed with #65
