### ISSUE TITLE
Kannan and Bachem Smith Form

### ISSUE THREAD

**Issue by bdsaunders** [linbox-team/linbox#75]
test-smith-form-kannan-bachem currently doesn't compile.  Fix.  In particular have kb smith form use standard polys.  Unify to work over both ints and polys?

**Comment by jgdumas** [comment]
Compilation is solved by https://github.com/linbox-team/linbox/pull/78.
But now it runs forever.

**Comment by jgdumas** [comment]
Well field().quo is called field().div so that is ok.
Now should we put normalize, areAssociates within the ring API ?

**Comment by jgdumas** [comment]
normalize, areAssociates are for now with poly-ring.
