### ISSUE TITLE
PolynomialRing and DensePolynomial do not adhere to ring api

### ISSUE THREAD

**Issue by gmh33** [linbox-team/linbox#77]
The PolynomialRing and DensePolynomial classes do not pass the standard testRing tests.

**Comment by bdsaunders** [comment]
I've pushed a fix to branch poly-smith-form

**Comment by bdsaunders** [comment]
PolynomialRing introduces a different Element type (than in Poly1Dom) and
thus members such as init, one, mOne, zero, etc. are missing.

However with the patch below to givaro's givpoly1dense.h (adding
cardinality, inv, and invin) now both Givaro::Poly1dom and
Givaro::Poly1FactorDom pass testRing and runBasicRingTests.  Note: inv is
applicable only to units.

I will work on a "runPIRTests" to be in test-field.h to check on the
interface for gcd related functions and maybe runEDTests to check on  the
qrem functions.  The ED interface has the goal of drop-in substitution
between ZZ reps and F[x] reps.  The PIR interface extends from those to
their homomorphic images modulo an element.  All this is important to the
SNF algorithms.

The likely result of all this will be proposed patches to both LB and Giv.

**Comment by jgdumas** [comment]
This particular issue is now solved by https://github.com/linbox-team/linbox/pull/78.
The branch poly-smith-form has many other diffs so was not used.
