### ISSUE TITLE
deterministic charpoly of [2^2000] hangs forever

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/linbox#87]
The current default variant is the probabilistic early termination Chinese Remainder Algorithm, which does not fail.
However, when turning on the deterministic variant with Hadamard bound computation for SageMath [1], the bug shows up.
This is due to a cast from 2^2000 (gmp integer) to double (=inf).

I fixed the SageMath patch turning the deterministic variant on. This issue is a reminder for when we implement the switch between the 2 variants in LinBox. 

[1] https://trac.sagemath.org/ticket/24214#comment:39

**Comment by ClementPernet** [comment]
828888ce6e465ec739e40b6ea98157304651d415  adds a regression test to catch it.

**Comment by Breush** [comment]
Currently designing a hadamard bound solution.
